//
//  PlaylistNames.swift
//  SuggestionPlatform
//
//  Created by Behrad Kazemi on 7/5/19.
//  Copyright © 2019 Behrad Kazemi. All rights reserved.
//

import Foundation
import Domain
struct PlaylistNames {
	let artist: Artist?
	
	private let artistRelayPrefixes = [
		"Mix Of ",
		"Best Of ",
		"Hottest ",
		"Listen To ",
		"GreatestHits Of ",
		"By ",
		""]
	
	private let commonPrefixes = [
		"Mix Of Day",
		"Hottest On Device",
		"Woah..",
		"Well Mixed",
		"Listen to these...",
		"Cool Mixes",
		"Now These...",
		"These are Awesome!",
		"Picky!",
		"Excellents",
		"Fantastics",
		"Gold!",
		"Good Ones",
		"Don't miss...",
		"Generated by Playor"]
	
	func generateTitle() -> String {
		if artist != nil {
			return (artistRelayPrefixes.randomElement() ?? "") + artist!.name
		}
		return commonPrefixes.randomElement() ?? "Auto Generated"
	}
	
}
